### ISSUE TITLE
Panel storing data along with dashboard settings

### ISSUE THREAD

**Issue by yesoreyeram** [yesoreyeram/yesoreyeram-boomtable-panel#26]
Panel is storing data along with settings. We are not supposed to store data . 

It is also annoying to see "unsaved changes" when navigate away from dashboard. (Do you want to save your changes? )

![image](https://user-images.githubusercontent.com/153843/39519481-d2664aaa-4dfe-11e8-8cb1-7da1fcd3efcf.png)

![image](https://user-images.githubusercontent.com/153843/39519294-15c235c6-4dfe-11e8-8eb6-8627969353a1.png)

**Comment by vhatsura** [comment]
Hi, @yesoreyeram.
First of all, thanks for awesome plugin. It's really wonderful.

We are using this plugin with Grafana 5.1.4 version. For our dashboards we are using provisioning feature. And for dashboards which is used you plugin it's hard to save dashboard, because in JSON panel has all datapoints. 

So, the main question, when are you going to fix this bug? Do you need some help with it?

**Comment by yesoreyeram** [comment]
@vhatsura Thanks for the feedback.  

Sorry. I am busy with other stuff so it is not possible for me to fix this bug anytime before July. Any kind of help is most appreciated. Feel free to create PRs if possible :) Thanks.

**Comment by yesoreyeram** [comment]
Hi @vhatsura . Thanks for the feedback.

New release created with fix. Please test and let me know your feedback.  Release [v0.3.0](https://github.com/yesoreyeram/yesoreyeram-boomtable-panel/releases/tag/v0.3.0)

**Comment by HannesHil** [comment]
Hi @yesoreyeram.

thanks for the plugin!

I have this exact problem with the plugin in Version 1.0.0
The Panel is storing datapoints into the Dashboard JSON. 

Is there any easy way to fix this?

**Comment by yesoreyeram** [comment]
@HannesHil  Can you post the panel json? I couldn't reproduce.

**Comment by HannesHil** [comment]
Thanks for your quick reaction. First of all your Panel is working correctly. 
Just after your comment I tried deleting the data fields in our dashboard json and now everything is like it should. I think we initialy exported the dashboard prior to your fix in version 0.3.0 and since than we had the data fields in the json. 	
It seems that unused Json fields remain untouched during the import and export of dashboards.

So sorry for bothering and awsome work :)
