### ISSUE TITLE
Stat Current does not show "No data" when there is no new Data Incoming

### ISSUE THREAD

**Issue by Links2004** [yesoreyeram/yesoreyeram-boomtable-panel#30]
Stat Current does not show "No data" when there is no new Data Incoming.

example:

![image](https://user-images.githubusercontent.com/974709/43661677-743b2a3c-9763-11e8-826f-a38fe939bb80.png)

![image](https://user-images.githubusercontent.com/974709/43661694-82aeb52a-9763-11e8-9e72-fc21b1680622.png)

if the graph is totally empty it is working as expected

![image](https://user-images.githubusercontent.com/974709/43661789-c584ceca-9763-11e8-989d-de3ee73a3c51.png)

**Comment by yesoreyeram** [comment]
I fear that this is the default behaviour of grafana. If the time range chosen as last X minutes, then the last non-null value in the X minutes is considered as latest. So unlike graph, we have to override time range to get the expected behaviour.   

Could you please check and confirm the scenario in table panel?

**Comment by Links2004** [comment]
can confirm that single Stats have the same problem

**Comment by yesoreyeram** [comment]
Sorry @Links2004 . This is the default / expected  behavior of grafana. Hence closing this. In case grafana fix this,  will merge it to this plugin.
