### ISSUE TITLE
Option to hide the first column and table header

### ISSUE THREAD

**Issue by rickbowden** [yesoreyeram/yesoreyeram-boomtable-panel#40]
Thanks for this panel, it looks like it could be useful for displaying metrics of multiple items.
Would it be possible to be able to hide the first column.
Example. When using the CloudWatch data source I query multiple loadbalancers for HealthyHostCount and SurgeQueue. I display these by repeating the panel for each loadbalancer.
This results in me displaying the loadbalancer name in the title AND in the first column.
![image](https://user-images.githubusercontent.com/22094101/47792405-e15ebe80-dd13-11e8-8c0e-be996ffaf1ed.png)

**Comment by yesoreyeram** [comment]
Thanks @rickbowden for the feature request. This is now implemented in master /  3ef4b1312c0f2ac846db852b330a7d53a65c0001 which is also released as [Version v0.4.5](https://github.com/yesoreyeram/yesoreyeram-boomtable-panel/releases/tag/v0.4.5)

![image](https://user-images.githubusercontent.com/153843/47859058-4fbf8180-dde5-11e8-8b27-2ef94919d1f8.png)

Couple of following options in the options tab will be introduced to achieve the above scenario

![image](https://user-images.githubusercontent.com/153843/47859088-64037e80-dde5-11e8-93b1-0cc18ee65d69.png)

Setup example
=========

![image](https://user-images.githubusercontent.com/153843/47859189-a9c04700-dde5-11e8-8647-3851863796ed.png)

![image](https://user-images.githubusercontent.com/153843/47859232-c492bb80-dde5-11e8-9d41-faf5a77d6b5e.png)

If you need metrics vertically, make the row names unique and column names same. 
Otherwise if you need metrics horizontally like the one showed in the original issue request, make column name unique and row name same. Example given below. 

You can use "Transform value" feature to show the details along with the metric

![image](https://user-images.githubusercontent.com/153843/47859548-75995600-dde6-11e8-8573-b998a5df7155.png)

Example of metrics shown horizontally

![image](https://user-images.githubusercontent.com/153843/47860151-cb223280-dde7-11e8-8ec5-35f5fd2be02a.png)

You can also use `_row_name_` or `_col_name_` in the value transform field

![image](https://user-images.githubusercontent.com/153843/47860953-9f07b100-dde9-11e8-8632-5563f01b5e15.png)


Feel free to test. If you see any issues or need more features, let me know.

BOOM,
Sriram

**Comment by rickbowden** [comment]
@yesoreyeram Thanks very much for adding this so quick.

**Comment by orena1** [comment]
Can you post a simple data structure that supports this feature?  thanks
